# Generated by Django 5.1.6 on 2025-02-20 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='flashcards.Folder', null=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, blank=True, to='flashcards.CustomUser'),
        ),
    ]
