# Generated by Django 5.1.6 on 2025-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcardset_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
