# Generated by Django 5.1.4 on 2025-02-19 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='question',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='term',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.flashcardset'),
        ),
    ]
