# Generated by Django 5.1.6 on 2025-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_is_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'name')},
        ),
    ]
