# Generated by Django 5.1.6 on 2025-02-20 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_create_default_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='flashcards.folder'),
            preserve_default=False,
        ),
    ]
