# Generated by Django 5.1.4 on 2025-02-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcardset_remove_flashcard_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='answer',
            new_name='definition',
        ),
    ]
