# Generated by Django 5.1.6 on 2025-02-20 18:35

from django.db import migrations, models
import django.db.models.deletion

def create_default_folder(apps, schema_editor):
    Folder = apps.get_model('flashcards', 'Folder')
    CustomUser = apps.get_model('flashcards', 'CustomUser')
    default_user = CustomUser.objects.first()  # Use the first user as the default user
    if not default_user:
        default_user = CustomUser.objects.create(username='defaultuser', email='default@example.com')
    Folder.objects.create(id=1, name='Default Folder', slug='default-folder', user=default_user)



class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_add_folder_and_user_to_flashcardset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='flashcards.CustomUser', null=True),
        ),
        migrations.RunPython(create_default_folder),
    ]
