# Generated by Django 5.1.6 on 2025-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_add_folder_and_user_to_flashcardset'),
    ]

    operations = [
         migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
