# Generated by Django 5.1.6 on 2025-02-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_make_folder_non_nullable'),
        ('flashcards', '0005_add_slug_to_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='flashcards.folder'),
            preserve_default=False,
        ),
    ]
