# Generated by Django 5.1.6 on 2025-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_make_user_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='term',
            field=models.CharField(default='', max_length=200),
        ),
    ]
